# Build and deploy documentation to GitHub pages on master push.

name: Deploy Docs

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      # TODO: Re-implement documentation website
