name: Lint files

on: push

jobs:
  lint:
    name: Lint files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.26.x
      - name: Check source code format
        run: deno fmt --check
      - name: Lint files
        run: deno lint
